### ISSUE TITLE
Main Icon

### ISSUE THREAD

**Issue by Kayeeec** [Kayeeec/NoFuzzMenu#1]
Make a main No Fuzz Menu Icon.

**Comment by Kayeeec** [comment]
![ic_launcher](https://user-images.githubusercontent.com/11568348/55506845-b972de80-5656-11e9-84b1-6de2d1100193.png)

![ic_launcher](https://user-images.githubusercontent.com/11568348/55506869-c394dd00-5656-11e9-841c-786106abd3e7.png)

**Comment by bkompis** [comment]
Done.
